### ISSUE TITLE
API frequently times out

### ISSUE THREAD

**Issue by bcl** [osbuild/rpmrepo#75]
When trying to list the snapshots using `curl https://rpmrepo.osbuild.org/v2/enumerate | jq .` it frequently responds with:

```
{
  "message": "Endpoint request timed out"
}
```

instead of the list of snapshots.

**Comment by bcl** [comment]
One way to improve this may be to generate the list at snapshot time and just serve it as a static file.

**Comment by achilleas-k** [comment]
should we close this issue now?  It's all solved right?

**Comment by bcl** [comment]
Yeah, this can be closed. I haven't noticed timeouts lately, but I think they can still happen. The actual solution was more ram IIRC.
