### ISSUE TITLE
Did we lose a user documentation page?

### ISSUE THREAD

**Issue by bcl** [osbuild/rpmrepo#93]
The README points to https://osbuild.org/rpmrepo/ as 'user documentation' but I am not sure that page ever existed :)

**Comment by achilleas-k** [comment]
IIRC, it used to link to this page: https://github.com/osbuild/osbuild.github.io/blob/1ee833241d0629545f7314f27530e714e921df93/docs/developer-guide/projects/rpmrepo/index.md

and then it got replaced by the project README and moved around.

**Comment by bcl** [comment]
Looks like this has been fixed for a while :)
